Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/xenial64"
	
	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network "private_network", ip: "192.168.33.10"
	  
	config.vm.network "public_network"

	config.vm.synced_folder "./backup", "/vagrant_data", create: true

	config.vm.provider "virtualbox" do |vb|
		vb.memory = "2048"
	end
	config.vm.provision "file", source: "/", destination: "/remote/IoT_HoneyPot"
	config.vm.provision "shell", inline: <<-SHELL
		apt-get update
		apt-get install apt-transport-https ca-certificates curl software-properties-common
		curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
		sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
		apt-get update
		apt-get install -y docker-ce
		apt-get install python3 python3-pip
        cd /remote/IoT_HoneyPot/IoT_HoneyPot
		python3-pip install -r requierements.txt
		# Sustituir la ip por la del servidor y el puerto por el puerto que se quiera usar para escuchar
		python3 simularYlogearDispositivoIoT.py localhost 21
        sudo usermod -aG docker $USER	
	SHELL
end